### ISSUE TITLE
Error: malformed database schema (Configuration) - near "STRICT": syntax error

### ISSUE THREAD

**Issue by rhclayto** [GrapheneOS/AttestationServer#139]
I am trying to add email alert configuration into the attestation.db, but I am getting the following error: 

`Error: malformed database schema (Configuration) - near "STRICT": syntax error`

Also, I get the same error when I open attestation.db with sqlite3 & try to show tables with `.tables`.

Any ideas what is wrong?

Update: When I removed 'STRICT' from all the table creation code in AttestationServer.java & redeployed, this error went away.

**Comment by thestinger** [comment]
`STRICT` was added in SQLite 3.37.0 released last month. The command line utility that you're using should work fine.

AttestationServer is using our own builds of sqlite4java's native code with an updated SQLite, a build system that's not deprecated and basic hardening enabled. If you're using our code unaltered, that should work fine. Our sqlite4java native code build requires a relatively up-to-date glibc since we didn't build it on an ancient OS. You would need to make your own build if you're on an old OS. That's also going to be a problem for the `sqlite3` command if it's out-of-date.

By removing `STRICT`, you've worked around that, but the behavior is not going to match the way it is supposed to be and it's not going to know it needs to migrate to tables with `STRICT` when it's provided after using an updated sqlite4java.

**Comment by thestinger** [comment]
We host it on Arch Linux so there's an assumption of up-to-date dependencies and since it's not client code we're going to be sticking to that. We're also going to be assuming up-to-date Java 17+, etc.
