### ISSUE TITLE
SIGSEGV error

### ISSUE THREAD

**Issue by nberlee** [GrapheneOS/AttestationServer#45]
Can't seem to get passed `SIGSEGV (0xb) at pc=0x000000000000d7c6, pid=30, tid=31`

I probably did do something wrong with the database. But I am not sure how to setup the configuration. Or possibly compiled with a wrong OpenJDK ( i am using 12)

This is what I did:
```bash
sqlite3 attestation.db "CREATE TABLE Configuration(key, value)"
sqlite3 attestation.db "INSERT INTO Configuration VALUES ('emailUsername', '$EMAIL_USERNAME'), ('emailPassword', '$EMAIL_PASSWORD'), ('emailHost', '$EMAIL_HOST'), ('emailPort', '$EMAIL_PORT')"
```

This is the stacktrace:

```
Current thread (0x0000555b2c459000):  JavaThread "main" [_thread_in_native, id=31, stack(0x00007fd5d3c25000,0x00007fd5d3d25ab0)]

Stack: [0x00007fd5d3c25000,0x00007fd5d3d25ab0],  sp=0x00007fd5d3d246f8,  free space=1021k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x000000000000d7c6
C  [libsqlite4java-linux-amd64-1.0.392.so+0x4ee50]  pager_write+0x370
C  [libsqlite4java-linux-amd64-1.0.392.so+0x68fcd]  sqlite3BtreeSetVersion+0x9d
C  [libsqlite4java-linux-amd64-1.0.392.so+0x773e2]  sqlite3VdbeExec+0x9142
C  [libsqlite4java-linux-amd64-1.0.392.so+0x78741]  sqlite3_step+0x2f1
C  [libsqlite4java-linux-amd64-1.0.392.so+0x7cf87]  sqlite3_exec+0xd7
C  [libsqlite4java-linux-amd64-1.0.392.so+0xa271f]  Java_com_almworks_sqlite4java__1SQLiteManualJNI_sqlite3_1exec+0x8f
j  com.almworks.sqlite4java._SQLiteManualJNI.sqlite3_exec(JLjava/lang/String;[Ljava/lang/String;)I+0
j  com.almworks.sqlite4java._SQLiteManual.sqlite3_exec(Lcom/almworks/sqlite4java/SWIGTYPE_p_sqlite3;Ljava/lang/String;[Ljava/lang/String;)I+32
j  com.almworks.sqlite4java.SQLiteConnection.exec(Ljava/lang/String;)Lcom/almworks/sqlite4java/SQLiteConnection;+86
j  app.attestation.server.AttestationServer.open(Lcom/almworks/sqlite4java/SQLiteConnection;Z)V+35
j  app.attestation.server.AttestationServer.main([Ljava/lang/String;)V+13
v  ~StubRoutines::call_stub
V  [libjvm.so+0x853bf2]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x3c2
V  [libjvm.so+0x8cd649]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) [clone .isra.68] [clone .constprop.221]+0x2a9
V  [libjvm.so+0x8cfa84]  jni_CallStaticVoidMethod+0x164
C  [libjli.so+0x4c4e]  JavaMain+0x9ce

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.almworks.sqlite4java._SQLiteManualJNI.sqlite3_exec(JLjava/lang/String;[Ljava/lang/String;)I+0
j  com.almworks.sqlite4java._SQLiteManual.sqlite3_exec(Lcom/almworks/sqlite4java/SWIGTYPE_p_sqlite3;Ljava/lang/String;[Ljava/lang/String;)I+32
j  com.almworks.sqlite4java.SQLiteConnection.exec(Ljava/lang/String;)Lcom/almworks/sqlite4java/SQLiteConnection;+86
j  app.attestation.server.AttestationServer.open(Lcom/almworks/sqlite4java/SQLiteConnection;Z)V+35
j  app.attestation.server.AttestationServer.main([Ljava/lang/String;)V+13
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x000000000000d7c6
```

**Comment by thestinger** [comment]
This looks like a NULL pointer dereference. This is probably a bug in the chosen Java SQLite bindings, although the bug is likely triggered by something you're doing.

I filed an issue about replacing it since it's very poorly maintained: https://github.com/GrapheneOS/AttestationServer/issues/38.

However, it's no longer abandoned and they seem to be slowly putting together an update:

https://bitbucket.org/almworks/sqlite4java/issues/89/upgrade-sqlite-to-the-latest-version-prior

**Comment by thestinger** [comment]
You should try deleting the database and starting up the server without a database present. It creates the database including the Configuration table. It's intended that you insert the configuration after the database is created by the server. It does this itself:

```
            attestationConn.exec(
                    "CREATE TABLE IF NOT EXISTS Configuration (\n" +
                    "key TEXT PRIMARY KEY NOT NULL,\n" +
                    "value NOT NULL\n" +
                    ")");
```

I'd guess that the issue is tied to you using a newer SQLite than the library is currently using, since they let it fall very out-of-date. SQLite is backwards compatible but maybe it's triggering a bug in the bindings or bundled SQLite library.

I'm replacing SQLite with an up-to-date version myself, but it's a major annoyance.

**Comment by nberlee** [comment]
Thx for the help. Deleting the database didn't do the trick
I tried the OpenJDK:11-slim (debian) container image tag which worked! So that SQLite library is old enough.

**Comment by thestinger** [comment]
That's weird. The SQLite version is determined by the sqlite4java library, not the Java version. It sounds like sqlite4java is broken in the environment you were using.

**Comment by thestinger** [comment]
I've forked sqlite4java and added a basic Makefile-based build system for the native code in order to update SQLite to 3.37.0. I don't want to take over maintenance of this code but the library is basically abandoned and sqlite-jdbc doesn't fit what we want at all since it screws up a bunch of stuff in order to map the SQLite API to the Java JDBC API.
