### ISSUE TITLE
 When "Verified Boot Hash" changed?

### ISSUE THREAD

**Issue by aniphreak** [GrapheneOS/AttestationServer#86]
Hi, i have a dumb question: If the hash changed on the attestation server, on that point, what would that mean?

**Comment by thestinger** [comment]
As explained in https://attestation.app/about it provides a hash of all data protected by verified boot, i.e. a hash of the entire OS.

**Comment by aniphreak** [comment]
Hi there, what is not clear for me is why it changed. I would like to know what may be the reasons. For example. Are automatic updates changes the verified hash boot? Is unlocking/relocking the bootloader the hashboot?

**Comment by thestinger** [comment]
It's a hash of all the OS images. I think it's self-explanatory.

**Comment by thestinger** [comment]
A specific official release of the OS has a specific verified boot hash.

It sounds like you're confusing the verified boot hash with the verified boot key hash, which is shown in the advanced information. The verified boot key corresponds to a specific OS + device model combination so that's already implicitly displayed in the normal data and it's enforced that it never changes. No reason to check it by hand.

**Comment by aniphreak** [comment]
Thanks for the clarification.
